### ISSUE TITLE
As a user, I would like a new view which allows the drawing of handwritten equations

### ISSUE THREAD

**Issue by izconcept** [jusleg/simple-calculator-FAMINGO#117]
**Story Points: 8**

**Epic #118**

**Risk**: LOW
The interface itself is not risky. It is in a contained view. The biggest risk happen when implementing the recognition with the UI.
**Priority**: HIGH
We need the UI first so we can do the implementation of the recognition.

## Description
A new view which lets users draw equations. 

## Mockup
See Epic #118 

## Acceptance Test
![image](https://user-images.githubusercontent.com/7155653/38282144-91b2e600-377c-11e8-97d1-3194f6570391.png)

# Tasks

- [x] **New view/GUI for drawing feature** - *5* Ideal hour(s) *TASK #119*
- [x] **Unit and Integration Testing for drawing feature** - *1.5* Ideal hour(s) *TASK #122*

**Comment by 0matleb2** [comment]
This user story seems to be incomplete or not described from the end-user perspective.

**Comment by izconcept** [comment]
The idea of the epic (#118) is to separate the actual camera application with the OCR/problem solving logic. The stories are still a work in progress. Feel free to edit the titles/description and add acceptance tests, tasks, and mockups so that they make more sense.
