### ISSUE TITLE
As a user I would like the calculations to work

### ISSUE THREAD

**Issue by almiche** [jusleg/simple-calculator-FAMINGO#16]
Story points: 8
Time estimation: 36 - 48 hours

Tasks:
- [x] Square root function needs to be fixed 
- [x] Input shouldn't be stored as a string to be parsed 
- [x] rewrite tests with new logic

**Comment by jusleg** [comment]
Story points repartition for this task:
* Brian: 2
* Justin: 3
* Michel: 3
