### ISSUE TITLE
Refactor Operation classes to use the singleton design pattern

### ISSUE THREAD

**Issue by almiche** [jusleg/simple-calculator-FAMINGO#26]
All operations should follow the singleton design pattern since there is no use for multiple instances of the operations class.

**Ideal-hour(s)** : 1 hour
**Risk:** LOW
**Priority:** LOW

**Comments:** This is not an urgent issue but in my opinion we should apply the singleton pattern to all operations classes in order to use less memory.

**Comment by almiche** [comment]
@jusleg thoughts ?

**Comment by jusleg** [comment]
Why as a developer? Why not just an issue ?
