### ISSUE TITLE
As a developper I want the random pop up box to no longer display

### ISSUE THREAD

**Issue by almiche** [jusleg/simple-calculator-FAMINGO#27]
It seems that at random times the original developper of this app decided to include a random pop up box about purchasing the pro version of the Simple apps suits. This needs to be removed from the app since all of our tests are being screwed up.
<img width="364" alt="screen shot 2018-02-09 at 4 29 57 pm" src="https://user-images.githubusercontent.com/14715156/36051128-11aa66ac-0db7-11e8-8ec6-aa51e0f64f7c.png">

**Comment by izconcept** [comment]
Fixed in PR #29 by forking and modifying 'simple-commons' library.
