### ISSUE TITLE
As a user I would like to have the power button back 

### ISSUE THREAD

**Issue by almiche** [jusleg/simple-calculator-FAMINGO#41]
**Story Points: 2**

Risk: LOW

Priority: LOW

## Description
The power function allows the user to calculate perform power operations on a number. For example, 5 to the power of 2, is 5 * 5 = 25.

## Mockup

![Mockup image]()
*Image describing the PR*

## Acceptance Test

| Test Reference | Test Date | Tester | Test Steps | Expected Result | Actual Result |
|----------------|-----------|--------|------------|-----------------|---------------|
| 1              |           |        |            |                 |               |
| 2              |           |        |            |                 |               |
| 3              |           |        |            |                 |               |
| 4              |           |        |            |                 |               |
| 5              |           |        |            |                 |               |

# Tasks

- [ ] **Task Name** - *x* Ideal hour(s) *TASK #*
- [ ] **Task Name** - *x* Ideal hour(s) *TASK #*
- [ ] **Task Name** - *x* Ideal Hour(s) *TASK #*

**Comment by izconcept** [comment]
This user story will be merged into #39
