### ISSUE TITLE
Android Backend Implementation for Taxes Feature

### ISSUE THREAD

**Issue by izconcept** [jusleg/simple-calculator-FAMINGO#64]
Task for user story #51 

**Ideal Hours: 5**

**Comment by miisaka** [comment]
Geolocation feature is completed but code needs some cleanup/minor refactoting and tests will need to be added

**Comment by miisaka** [comment]
![device-2018-03-08-022049](https://user-images.githubusercontent.com/14710011/37138299-99bd9076-2277-11e8-85b0-21181c91ec81.gif)
